# Generated by Django 2.2.6 on 2019-11-01 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bailarina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance.Bailarina')),
                ('teatro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance.Teatro')),
            ],
        ),
        migrations.AddField(
            model_name='teatro',
            name='bailarinas',
            field=models.ManyToManyField(through='dance.Show', to='dance.Bailarina'),
        ),
    ]
