# Generated by Django 2.2.6 on 2019-11-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance', '0002_auto_20191031_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='fecha',
        ),
    ]
